Fix compilation error - add missing esp_ipa_config_t type definition
The type esp_ipa_config_t was being used in esp_video_init.c and version.c
but was not defined in any header, causing compilation errors:

  error: unknown type name 'esp_ipa_config_t'
  error: implicit declaration of function 'esp_ipa_pipeline_get_config'

Changes:
1. Added esp_ipa_config_t type definition in esp_ipa_types.h:
   - ipa_nums: Number of IPA algorithms
   - ipa_names: Array of IPA algorithm names

2. Added function declaration in esp_ipa.h:
   - esp_ipa_pipeline_get_config() - Get IPA config for camera sensor

This type is used to configure the ISP pipeline with the appropriate
image processing algorithms (AWB, sharpening, denoising, etc).

Fixes compilation errors in esp_video_init.c line 483