Fix undefined reference to rmdir in webdavbox3
Replace rmdir() with remove() which is properly implemented
in ESP-IDF VFS for RISC-V targets. Both functions work for
empty directories.