Fix include path for ov02c10_custom_formats.h in ov02c10.c
Fixed compilation error:
- fatal error: ov02c10_custom_formats.h: No such file or directory

Root cause: ov02c10.c is in sensor/ov02c10/ subdirectory
but ov02c10_custom_formats.h is in esp_cam_sensor/ (2 levels up)

Solution: Changed include from:
  #include "ov02c10_custom_formats.h"
to:
  #include "../../ov02c10_custom_formats.h"

Now compilation should find the header file.